import pygame, pygame.locals, sys
from engine.scene import *
from engine.component import *
from engine.actor import *
from engine.staticspritecomponent import *

pygame.init()

# setup the window
window = pygame.display.set_mode((300, 600), 0, 32)
pygame.display.set_caption("Titolo bellissimo")

# Global state variable
Quit = False
scene = Scene()

component = StaticSpriteComponent("faccina.png", window.get_rect())
actor = Actor()
actor.components.append(component)
scene.actors.append(actor)

scene.load()

def process_events():
    global Quit
    # process all the events generated by the system
    for event in pygame.event.get():
        # event QUIT is generated when the user closes the application window
        if event.type == pygame.locals.QUIT:
            Quit = True

def update_game_logic():
    global scene
    
    scene.update()

    return

def render():
    global scene

    # clear the screen
    BLACK = (0, 0, 0)
    WHITE = (255, 255, 255)
    window.fill(BLACK)

    scene.render(window)
    
    # update the display with the new content of the window
    pygame.display.update()

# game loop
while not Quit:
    process_events()
    
    update_game_logic()
    
    render()

pygame.quit()
sys.exit()