import pygame, pygame.locals, sys

pygame.init()

# setup the window
window = pygame.display.set_mode((300, 600), 0, 32)
pygame.display.set_caption("Titolo bellissimo")


# Global state variable
Quit = False

def process_events():
    global Quit
    # process all the events generated by the system
    for event in pygame.event.get():
        # event QUIT is generated when the user closes the application window
        if event.type == pygame.locals.QUIT:
            Quit = True

def update_game_logic():
    # do nothing at this moment
    return

def render():
    # clear the screen
    BLACK = (0, 0, 0)
    WHITE = (255, 255, 255)
    window.fill(BLACK)

    # Print hello world
    font = pygame.font.SysFont(None, 48)
    text = font.render('Hello World', True, WHITE)
    textRect = text.get_rect()
    textRect.centerx = window.get_rect().centerx
    textRect.centery = window.get_rect().centery
    window.blit(text, textRect)
    
    # update the display with the new content of the window
    pygame.display.update()

# game loop
while not Quit:
    process_events()
    
    update_game_logic()
    
    render()

pygame.quit()
sys.exit()