import pygame, pygame.locals, sys

pygame.init()

# setup the window
window = pygame.display.set_mode((300, 600), 0, 32)
pygame.display.set_caption("Titolo bellissimo")

# Load up the assets
image = pygame.image.load("faccina.png")

# Global state variable
x = 30
y = 20
vx = 0.05
vy = 0.05
Quit = False

def process_events():
    global Quit
    # process all the events generated by the system
    for event in pygame.event.get():
        # event QUIT is generated when the user closes the application window
        if event.type == pygame.locals.QUIT:
            Quit = True

def update_game_logic():
    global x, y, vx, vy
    x += vx
    y += vy

    # bounce on the x axis
    if x < 0 or x > window.get_rect().width:
        vx = -vx
    
    # bounce on the y axis
    if y < 0 or y > window.get_rect().height:
        vy = -vy
    
    return

def render():
    # clear the screen
    BLACK = (0, 0, 0)
    WHITE = (255, 255, 255)
    window.fill(BLACK)

    # Print hello world
    rect = image.get_rect()
    rect.centerx = x
    rect.centery = y
    window.blit(image, rect)
    
    # update the display with the new content of the window
    pygame.display.update()

# game loop
while not Quit:
    process_events()
    
    update_game_logic()
    
    render()

pygame.quit()
sys.exit()